apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0b21teWRldnYxIiwicGFzc3dvcmQiOiI5MTFhbmR5RG9DMCIsImVtYWlsIjoibGNrLmxjazAxQGdtYWlsLmNvbSIsImF1dGgiOiJkRzl0Ylhsa1pYWjJNVG81TVRGaGJtUjVSRzlETUE9PSJ9fX0=
  config.json: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0b21teWRldnYxIiwicGFzc3dvcmQiOiI5MTFhbmR5RG9DMCIsImVtYWlsIjoibGNrLmxjazAxQGdtYWlsLmNvbSIsImF1dGgiOiJkRzl0Ylhsa1pYWjJNVG81TVRGaGJtUjVSRzlETUE9PSJ9fX0=
kind: Secret
metadata:
  creationTimestamp: "2022-10-18T03:20:37Z"
  name: dockercred
  namespace: jenkins-server
  resourceVersion: "12618"
  uid: 3fbac850-2a5c-49d4-914a-9598bc9ae926
type: kubernetes.io/dockerconfigjson
