apiVersion: v1
data:
  .dockerconfigjson: empty
  config.json: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ0b21teWRldnYxIiwicGFzc3dvcmQiOiI5MTFhbmR5RG9DMCEwIiwiZW1haWwiOiJsY2subGNrMDFAZ21haWwuY29tIiwiYXV0aCI6ImRHOXRiWGxrWlhaMk1UbzVNVEZoYm1SNVJHOURNQ0V3In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2022-10-18T13:38:07Z"
  name: dockercred
  namespace: jenkins-server
  resourceVersion: "9888"
  uid: 9c8cc0ad-d8de-460c-a961-95f6f5ac516f
type: kubernetes.io/dockerconfigjson
