apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-persistent-volume
  namespace: jenkins
spec:
  storageClassName: jenkins-persistent-volume
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/jenkins-volume/
